PersonelTakip/PersonelTakip/Controllers/PersonelController.cs
using PersonelTakip.Models.Veritabani;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace PersonelTakip.Controllers
{
    
    public class PersonelController : Controller
  
    {
        MVCPersonelEntities db = new MVCPersonelEntities();
        // GET: Personel

        public ActionResult Index(string ara,int sayfa=1)
        {
            return View(db.TBLPersonel.Where(x=>x.AdiSoyadi.Contains(ara)||ara==null).ToList().ToPagedList(sayfa,3));
        }

        [HttpGet]
        public ActionResult Ekle()
        {
            ViewBag.DepartmanID = new SelectList(db.TBLDepartman, "ID", "Departman");
            return View();
        }

        [HttpPost]
        public ActionResult Ekle(TBLPersonel P)
        {
      
            db.TBLPersonel.Add(P);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult GuncelleBilgiGetir(TBLPersonel P)
        {
            P = db.TBLPersonel.Find(P.ID);
            ViewBag.DepartmanID = new SelectList(db.TBLDepartman, "ID", "Departman", P.DepartmanID);
            return View(P);
        }

        public ActionResult Guncelle(TBLPersonel P)
        {

            db.Entry(P).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult SilBilgiGetir(TBLPersonel P)
        {
            P = db.TBLPersonel.Find(P.ID);

            return View(P);
        }

        public ActionResult Sil(TBLPersonel P)
        {
            P = db.TBLPersonel.Find(P.ID);
            db.Entry(P).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PersonelTakip/PersonelTakip/Views/Personel/Ekle.cshtml
@{
    ViewBag.Title = "Ekle";
}

<h2>Personel Ekleme Sayfası</h2>

<form class="form-group" method="post">

    <div class="container">
        <label>Personel Adı Soyadı</label>
        <input type="text" class="form-control" name="AdiSoyadi"required />
        <br />
        <label>Departman</label>
      @Html.DropDownList("DepartmanID",null,new {@class="form-control"})
        <br />
        <label>Telefon</label>
        <input type="text" class="form-control" name="Telefon" required />
        <br />
        <label>Sehir</label>
        <input type="text" class="form-control" name="Sehir"required />
        <br />
        <label>Email</label>
        <input type="text" class="form-control" name="Email" required/>
        <br />
        <label>Tarih</label>
       @Html.TextBox("Tarih","",new {@class="form-control"})
        <br />
    </div>
    <div> <button class="btn btn-primary">Yeni Ekle</button></div>

</form>

PersonelTakip/PersonelTakip/Views/Personel/GuncelleBilgiGetir.cshtml
@model PersonelTakip.Models.Veritabani.TBLPersonel
@{
    ViewBag.Title = "GuncelleBilgiGetir";
}

<h2>Personel Güncelleme Sayfası</h2>

@using (Html.BeginForm("Guncelle", "Personel", FormMethod.Post))
{
    <label>ID</label>
    @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
    <label>Ad Soyad </label>
    @Html.TextBoxFor(x => x.AdiSoyadi, new { @class = "form-control" })
    <label>Departman</label>
    @Html.DropDownList("DepartmanID",null,new {@class="form-control"})
    <label>Telefon</label>
    @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
    <label>Şehir</label>
    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })
    <label>E-Mail</label>
    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
    <label>Tarih</label>
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
    @Html.ActionLink("Ana Sayfa", "Index", null, new { @class = "btn btn-primary" })

}

PersonelTakip/PersonelTakip/Views/Personel/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model PagedList.IPagedList<PersonelTakip.Models.Veritabani.TBLPersonel>
@{
    ViewBag.Title = "Index";
}
<br />
@using (Html.BeginForm())
{
    <label>Personel Ara:</label>
    @Html.Editor("ara")
    <input type="submit" value="ara" class="btn btn-primary" />
}
<h2>Personel Listesi</h2>

<table class="table table-bordered">
    <h3 class="text-center">Personeller</h3>
    <tr>
        <th>ID</th>
        <th>Adı Soyadı</th>
        <th>Departman</th>
        <th>Telefon</th>
        <th>Şehir</th>
        <th>Email</th>
        <th>Tarih</th>
        <th>Güncelle</th>
        <th>Sil</th>
    </tr>
    @for (int i = 0; i < Model.Count; i++)
    {
        <tr>
            <th>@Model[i].ID</th>
            <td>@Model[i].AdiSoyadi</td>
            <td>@Model[i].TBLDepartman.Departman</td>
            <td>@Model[i].Telefon</td>
            <td>@Model[i].Sehir</td>
            <td>@Model[i].Email</td>
            <td>@Model[i].Tarih</td>
            <td><a href="/Personel/GuncelleBilgiGetir/@Model[i].ID" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Personel/SilBilgiGetir/@Model[i].ID" class="btn btn-danger">Sil</a></td>


        </tr>
    }

</table>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))
Toplam @Model.TotalItemCount Kayıt Listelendi. Bu sayfada @Model.FirstItemOnPage ile @Model.LastItemOnPage arasında kayıt listelendi.
<br />
<br />
<a href="/Personel/Ekle/" class="btn btn-primary"> Yeni Personel Ekle</a>

PersonelTakip/PersonelTakip/Views/Personel/SilBilgiGetir.cshtml
@model PersonelTakip.Models.Veritabani.TBLPersonel
@{
    ViewBag.Title = "SilBilgiGetir";
}

<h2>Personel Silmek İstediğinize Emin misiniz ? </h2>

@using (Html.BeginForm("Sil", "Personel", FormMethod.Post))
{
    <label>ID</label>
    @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
    <label>Ad Soyad </label>
    @Html.TextBoxFor(x => x.AdiSoyadi, new { @class = "form-control" })
    <label>Departman</label>
    @Html.TextBoxFor(x=>x.TBLDepartman.Departman,new {@class="form-control"})
    <label>Telefon</label>
    @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
    <label>Şehir</label>
    @Html.TextBoxFor(x => x.Sehir, new { @class = "form-control" })
    <label>E-Mail</label>
    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
    <label>Tarih</label>
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br/>
    <button class="btn btn-danger">Sil</button>
    @Html.ActionLink("Ana Sayfa", "Index", null, new { @class = "btn btn-primary" })
}